version: '3.9'

services:
    backend:
        build:
            context: ./proxy-web-backend
            dockerfile: ./Dockerfile
        image: "proxy-web-backend"
        ports:
            - "20000:15000"
        environment:
            - REDIS_HOST=redis-.cloud.redislabs.com
            - REDIS_PORT=19831
            - REDIS_PASSWORD=wAWx2noLx9OfXrDrn4djZ
            - REDIS_USERNAME=default
            - ASPNETCORE_ENVIRONMENT=Development
            - PORTS=8000,443,8080, 8081,1194,3128
            - MONGODB_URL=mongodb+srv://NestApp:Aghjghj8q@clusternest.jghjghod3.mongodb.net/ProxyIpDB?retryWrites=true&w=majority
    frontend:
        build:
            context: ./proxy-web-ui
            dockerfile: ./Dockerfile
        image: "proxy-web-ui"
        ports:
            - "3000:80"
        environment:
            - REACT_APP_API_URL=http://localhost:20000


